#!/bin/bash
function die()
{
    echo $*
    exit 1
}

rm -rf tmp

./build.py memcached
if [ ! $? -eq 0 ]; then
    die "Encountered error building memcached.  Check messages and try again."
fi

./build.py memcachedb
if [ ! $? -eq 0 ]; then
    die "Encountered error building memcachedb.  Check messages and try again."
fi

cp -r tools/* tmp/tar/dolomite-env/bin

cd tmp/tar

tar cvvfz ../tools-ubuntu-8.10.tgz .
